### ISSUE TITLE
Some contents are rendered too late

### ISSUE THREAD

**Issue by memeplex** [Myriad-Dreamin/shiroa#50]
While reading https://myriad-dreamin.github.io/typst.ts/cookery/ I noticed that some contents (I believe in every case they were contents of raw blocks, but I cannot say for sure) were loaded after the initial page rendering, when they became exposed while I was scrolling through the page, but with noticeable lag so that I was able to see an empty box being filled with text a fraction of a second later.

**Comment by memeplex** [comment]
Here is an example:

https://github.com/Myriad-Dreamin/typst-book/assets/2845433/3c261f52-0b4d-4694-89f0-5e0fc6bf885c

**Comment by Myriad-Dreamin** [comment]
This (typst.ts cookery book) and the documentation of typst-book is the experimental deployment of the [DOM export](https://github.com/Myriad-Dreamin/typst.ts/tree/main/exporter/dom). The DOM export has much better performance and text selection support than previous pure SVG export, but is definitely more bug-prone.

I have fixed tons of bugs in the DOM export and this issue is also fixed. This issue is caused by incorrect calculation of bounding boxes of typst elements.

**Comment by Myriad-Dreamin** [comment]
My plan is to make a new publish on typst v0.11.0. And typst v0.11.0 will come in near future.

**Comment by ice1000** [comment]
Here's a slightly longer document that you guys can test with: https://ice1000.org/lnl-modal/report.html

The source code is available here: https://github.com/ice1000/website

**Comment by Myriad-Dreamin** [comment]
> Here's a slightly longer document that you guys can test with: https://ice1000.org/lnl-modal/report.html
> 
> The source code is available here: https://github.com/ice1000/website

It's very cursed to render a long page, but I'm working on it. To relieve it, you can break report into pages, as rendering are lazy across pages.

**Comment by Myriad-Dreamin** [comment]
It has rendered the typst.ts documentation and ice1000's website like a flash in v0.1.5!
